// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <nav></nav>
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

import { Inter } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        {/* Add other head elements as needed */}
      </Head>
      <Navbar />
      <body className={inter.className}>{children}</body>
      <Footer />
    </>
  )
}
